### PR TITLE
Project rename proposal, version updates

### PR DESCRIPTION
**Pull request by Sanne**
If there are no objections, I'll also change the repository name to match.

### CODE REVIEW

**Comment by Sanne** [comment]
Since I guess you're not setup for notifications, forgive me the direct mention:

@gunnarmorling @gsmet @DavideD @yrodiere 

Context: In Hibernate Search we want to start using these. We're not using them yet so would be good to settle the name first.
@yrodiere already proposed a similar naming scheme for the future of other similar packages, as the JDK9 era is making the original names confusing.

**Comment by yrodiere** [comment]
@Sanne Seems like a good idea to me. I first wondered if we shouldn't rather use `-wildflymodule`, but it seems even the Wildfly website still call them "JBoss" modules, so it makes sense :)

**Comment by gsmet** [comment]
@yrodiere tbh, I had the same hesitation.

JBoss Modules is the technical name of the underlying component but from a user point of view, these modules are for WildFly. So I must admit I would prefer to use `wildfly-modules` (with a dash) but that might be just me.

**Comment by yrodiere** [comment]
@gsmet @Sanne Right... Also, we named an artifact `hibernate-search-wildfly-testingmodules` [recently](https://github.com/hibernate/hibernate-search/pull/1577), so `wildfly-modules` would be more consistent.

**Comment by Sanne** [comment]
These are not just for WildFly but also for JBoss EAP .. does it make more sense in this context?

Not least the modules format is called `JBoss Modules`.

**Comment by yrodiere** [comment]
> These are not just for WildFly but also for JBoss EAP .. does it make more sense in this context?

So are the testing modules in `hibernate-search-wildfly-testingmodules`, since they are very likely to be used during productization... ? Yet we used "wildfly" in the artifact name.

Also, JBoss is "wildfly with extras", so in a sense using the world "wildfly" (which relates to both WidlFly and JBoss EAP) would be more generic than using the word "jboss" (which only relates to JBoss EAP). And that's very visible in how we wrote Hibernate Search's documentation, by the way: we primarily mention WildFly, not JBoss EAP.

But I must admit that the WildFly project using the terms "JBoss Modules" [on its website](http://wildfly.org/about/) makes a strong case for the "jboss-modules" naming scheme.

Anyway, both naming schemes make sense in my opinion, but we should pick one and stick to it. Not use one here for lucene modules, and another one in the Hibernate Search project with `hibernate-search-wildfly-testingmodules` (and possibly in the future name of `hibernate-search-modules`).

**Comment by Sanne** [comment]
Please consider that the name for `hibernate-search-wildfly-testingmodules` is irrelevant as we don't distribute that one, it's merely intended for running our own integration tests - which we typically do on WildFly. Sure, one can override this an use JBoss EAP instead but then you know what you're doing.

> Also, JBoss is "wildfly with extras"

No, you're mistaken. JBoss EAP is exactly the same as WildFly, the only "extras" is the additional thousand of hours of testing in extreme conditions and the strings attached, e.g. the support one can get, legal coverage, etc... On top of this it's all rebuilt from sources (including the operating system, compilers and the JDK) to make sure nothing dodgy slips in from any level.
We're never adding anything to it which isn't also available in the upstream projects; even the bugfixes which will be necessary after all those tests are applied to upstream first - just they will appear in the next version of course as the one which EAP uses as a base will already have been tagged.
The opposite might be true: if some new feature is identified as being too problematic during QA it might be removed from EAP, so essentially EAP is a subset of WildFly features, plus backported patches.

More importantly: the *JBoss Modules* structure is used by some projects beyond WildFly/EAP, it's known as *JBoss Modules* by people in the circles of modular systems, etc..

I hope that's convincing enough :-)

I guess I have to decide. We're going to use `JBoss Modules` over `WildFly Modules`.

**Comment by yrodiere** [comment]
> Please consider that the name for `hibernate-search-wildfly-testingmodules` is irrelevant as we don't distribute that one, it's merely intended for running our own integration tests - which we typically do on WildFly. Sure, one can override this an use JBoss EAP instead but then you know what you're doing.

So eventually we'll have `hibernate-search-wildfly-testingmodules` just beside `hibernate-search-jbossmodules`? And you're fine with that? Come on.

>> Also, JBoss is "wildfly with extras"
>
> No, you're mistaken. JBoss EAP is exactly the same as WildFly, the only "extras" is the additional thousand of hours of testing in extreme conditions and the strings attached, e.g. the support one can get, legal coverage, etc...

Yep, that's what I meant.

> More importantly: the *JBoss Modules* structure is used by some projects beyond WildFly/EAP, it's known as *JBoss Modules* by people in the circles of modular systems, etc..
> I hope that's convincing enough :-)

Yes. JBoss modules it is :)

Can I submit a PR to your repo to rename `hibernate-search-wildfly-testingmodules` to `hibernate-search-jbossmodules-testing` in [your PR](https://github.com/hibernate/hibernate-search/pull/1577), though? It's really itching me :-/

**Comment by Sanne** [comment]
> Can I submit a PR to your repo to rename hibernate-search-wildfly-testingmodules to hibernate-search-jbossmodules-testing in your PR, though? It's really itching me

Feel free but .. I'm not sure that's a better name.

`jbossmodules-testing` suggests it's meant either for:

1. people to do testing, like it contained useful testing helpers (it doesn't)
2. we're testing JBoss Modules (we don't..)

Not saying the existing name is significantly better but I do feel it's a bit less confusing - ultimately I don't care though as it's an internal only thing it has a good name as long as it doesn't confuse us (and other contributors to some extent).

**Comment by yrodiere** [comment]
It looks good, and I even tested it as part of another work in progress: https://github.com/hibernate/hibernate-search/pull/1599

So let's merge and change the name of the GitHub project accordingly? Ok @Sanne?

**Comment by Sanne** [comment]
> So let's merge and change the name of the GitHub project accordingly? Ok @Sanne?

+1 

Preparing for merge, and I'll rename the repository. Remember to update your git references..

**Pull request merged**
